### ISSUE TITLE
Connect Deconz

### ISSUE THREAD

**Issue by David8288** [SpaceinvaderOne/Home_Assistant_inabox#3]
Is it possible to set up a function for the deconz zigbee sticks via the Docker?

**Comment by SpaceinvaderOne** [comment]
If you want to add your deconz stick just plug the stick into your server. then edit the vm template to passthrough the stick.
You can then configure it in HA.
The Docker container, it only installs the HA vm.  The VM is how HA is running.

**Comment by David8288** [comment]
Thank you
